### ISSUE TITLE
$mail->reply_to doesn't work 

### ISSUE THREAD

**Issue by hsleewis** [fuel/email#10]

**Comment by frankdejonge** [comment]
This isn't very helpful... Which driver are you using? Can you send me headers? What's the code you've used to get to this conclusion?

**Comment by dhrrgn** [comment]
Seriously.  You need to provide more information than "It doesn't work".  That is just ridiculous.  Provide more information or we close the ticket.  We aren't going to waste our time trying to figure out what you mean.

**Comment by tomschlick** [comment]
Im pretty sure it does work (I use it daily). My guess is that he is running on code before my fix in #6 was applied.

**Comment by hsleewis** [comment]
Hi Guys,

Sorry if I wasn't a bit clearer.

I downloaded the package yesterday.
The mail does arrive, but no matter what I do, the reply_to doesn't work even if I only fill in the email address.

I'm using the default config.

And this is my code:

```
// Create an instance
$email = Email::forge();

// Set the from address
$email->from('xxxxxxxxxxx', 'test');        
// Set the to address
$email->to('xxxxxxxxxxx');
$email->reply_to( $data['email'], $data['firstname'].' '.$data['lastname'] );

// Set a subject
$email->subject('Contactform [#'.uniqid().'] '.$data['subject']);       

$message = 'name: '.$data['firstname'].' '.$data['lastname']." \n ";
$message .= 'email: '.$data['email']." \n ";
$message .= 'subject: '.$data['subject']." \n ";
$message .= 'message: '." \n "." \n ".$data['message']." \n ";

// And set the body.
$email->body( $message );

$email->send();
```

**Comment by dhrrgn** [comment]
Make sure you are looking at the right information in your mail client...they all display the "Reply To" address differently.  Can you post the raw email message including headers?

**Comment by hsleewis** [comment]
```
Return-Path: <xxxxxxxxxxx>
X-Spam-Checker-Version: SpamAssassin 3.3.1 (2010-03-16) on ctu.hs-l.nl
X-Spam-Level: ****
X-Spam-Status: No, score=4.9 required=5.0 tests=RCVD_IN_PBL,RCVD_IN_SORBS_DUL,
    RDNS_DYNAMIC,TO_NO_BRKTS_DYNIP autolearn=no version=3.3.1
X-Original-To: xxxxxxxxxxx
Delivered-To: xxxxxxxxxxx
Received: from virtual.domain.tld (xxxxxxxxxxx [xx.xx.xx.xx])
    by xxxxxxxxxxx (Postfix) with ESMTP id C6F328F342
    for <xxxxxxxxxxx>; Tue, 15 Nov 2011 23:51:34 +0100 (CET)
Received: by virtual.domain.tld (Postfix, from userid 70)
    id E97925CA996; Tue, 15 Nov 2011 23:53:02 +0100 (CET)
To: xxxxxxxxxxx
Subject: Contactform [#4ec2ed4ec2b56] Request custom color
Date: Tue, 15 Nov 2011 22:53:02 +0000
From: test <xxxxxxxxxxx>
Message-ID: <xxxxxxxxxxx>
X-Priority: 3 (Normal)
X-Mailer: FuelPHP, PHP 5.3 Framework
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"

name: Harold Leewis 
 email: bladiebla@xxxxxxxxxxx.nl 
 subject: Request custom color 
 message:  

 asfdasdasda
```
